devops: Run valgrind and sanitizers for all os-compiler combinations
Letting all tests for each combination run in one job costs less GH Actions
minutes than splitting each into their own job, even though that would
be more convenient.
The extra time that takes per run does not matter since the cpp-linter
workflow is longer.

Also highlight detected issues in logs in color.

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -1,6 +1,10 @@
 # Build and test the project on multiple OS and compiler configurations.
-# Tests are run by 'make test' and 'make testv'.
-# Valgrind and sanitizers are used in some configurations.
+# Tests are run three times via 'make test/testv': normally, with Valgrind
+# (Linux only), and with ASan+UBSan.
+# Test steps fail only if a test failed; Valgrind and sanitizer issues are only
+# reported when checking the logs in subsequent steps.
+# Failed tests do not stop a job to allow all configurations to run. In the end,
+# the workflow reports failure if any step in any job failed.
 
 name: Build and Test
 
@@ -18,7 +22,7 @@ concurrency:
 
 jobs:
   build-and-test:
-    name: ${{ matrix.os }} - ${{ matrix.compiler }} - ${{ matrix.test }}-${{ matrix.preset }}
+    name: ${{ matrix.os }} - ${{ matrix.compiler }}
     runs-on: ${{ matrix.os }}
 
     strategy:
@@ -34,42 +38,34 @@ jobs:
         include:
           - os: ubuntu-22.04
             compiler: clang++-12
-            compiler-package: clang-12
+            compiler-pkgs: clang-12 llvm-12-dev
             cmake-version: 3.22.1
-            preset: debug
-            test: testv
-          - os: ubuntu-latest
-            compiler: clang++-20
-            compiler-package: clang-20
-            preset: san
-            test: test
           - os: ubuntu-22.04
             compiler: g++-10
             cmake-version: 3.22.1
-            preset: debug
-            test: test
+          - os: ubuntu-latest
+            compiler: clang++-20
+            compiler-pkgs: clang-20 libclang-rt-20-dev llvm-20-dev
           - os: ubuntu-latest
             compiler: g++-14
-            preset: default
-            test: test
           - os: macos-latest
             compiler: c++
-            preset: san
-            test: test
 
     steps:
       - uses: actions/checkout@v5
       - name: Install compiler
-        if: matrix.compiler-package
-        run: sudo apt-get install ${{ matrix.compiler-package }} -y
+        if: matrix.compiler-pkgs
+        run: |
+          sudo apt-get install --no-install-recommends -y ${{ matrix.compiler-pkgs }}
+          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/${{ matrix.compiler }} 100
       - name: Install CMake ${{ matrix.cmake-version }}
         if: matrix.cmake-version
         uses: jwlawson/actions-setup-cmake@v2
         with:
           cmake-version: ${{ matrix.cmake-version }}
-      - name: Install Valgrind
-        if: matrix.test == 'testv'
-        run: sudo apt-get install valgrind -y
+      - name: Install Valgrind (Linux)
+        if: runner.os == 'Linux'
+        run: sudo apt-get install --no-install-recommends -y valgrind
       - name: Print versions
         run: |
           echo -e "--- Compiler ---"
@@ -78,40 +74,61 @@ jobs:
           cmake --version
           echo -e "\n--- Make ---"
           make --version
-          if [ ${{ matrix.test }} = testv ]; then
+          if [ ${{ runner.os }} = Linux ]; then
             echo -e "\n--- Valgrind ---"
             valgrind --version
           fi
-      - name: Build project
-        run: make CXX=${{ matrix.compiler }} PRESET=${{ matrix.preset }}
-      - name: Run tests
+
+      - name: Build normally
+        id: build-normal
+        run: make CXX=${{ matrix.compiler }}
+      - name: Run tests normally
         run: |
-          set +e
-          make ${{ matrix.test }} PRESET=${{ matrix.preset }}
-          if [ $? -ne 0 ]; then
-            echo "::error::Test failed."
-            EXIT_CODE=1
-          fi
-          set -e
-          if [ ${{ matrix.test }} = testv ]; then
-            cat build/${{ matrix.preset }}/Testing/Temporary/LastDynamicAnalysis_*.log
-            LOGS=$(cat build/${{ matrix.preset }}/Testing/Temporary/MemoryChecker.*.log)
-            if [ -n "$LOGS" ]; then
-              echo "$LOGS"
-              echo "::error::Valgrind detected issues."
-              EXIT_CODE=$((EXIT_CODE | 2))
-            fi
-          else
-            LOGS=$(cat build/${{ matrix.preset }}/Testing/Temporary/LastTest.log)
+          set -o pipefail
+          make test ARGS=-VV | grep --color=always --line-buffered -E "FAILED|$"
+
+      - name: Build with 'debug' preset
+        id: build-debug
+        if: ${{ !cancelled() && steps.build-normal.outcome == 'success' }}
+        run: make CXX=${{ matrix.compiler }} PRESET=debug
+      - name: Run tests with Valgrind (Linux)
+        if: ${{ runner.os == 'Linux' && !cancelled() && steps.build-debug.outcome == 'success' }}
+        run: |
+          set -o pipefail
+          make testv PRESET=debug ARGS=-VV | grep --color=always --line-buffered -E "FAILED|$"
+      - name: Check Valgrind logs (Linux)
+        if: ${{ runner.os == 'Linux' && !cancelled() && steps.build-debug.outcome == 'success' }}
+        run: |
+          LOGS=$(cat build/debug/Testing/Temporary/MemoryChecker.*.log)
+          if [ -n "$LOGS" ]; then
             echo "$LOGS"
-            if [ ${{ matrix.preset }} = san ]; then
-              if echo "$LOGS" | grep --ignore-case --color=always "Sanitizer"; then
-                echo "::error::Sanitizers detected issues."
-                EXIT_CODE=$((EXIT_CODE | 2))
-              fi
-            fi
+            exit 1
+          else
+            echo "No Valgrind issues detected."
           fi
-          exit $EXIT_CODE
+
+      - name: Build with 'san' preset
+        id: build-san
+        if: ${{ !cancelled() && steps.build-normal.outcome == 'success' }}
+        run: make CXX=${{ matrix.compiler }} PRESET=san
+      - name: Run tests with ASan and UBSan
+        if: ${{ !cancelled() && steps.build-san.outcome == 'success' }}
+        env:
+          ASAN_OPTIONS: check_initialization_order=1:detect_stack_use_after_return=1:exitcode=0:print_stats=1:print_summary=1
+          UBSAN_OPTIONS: print_stacktrace=1:print_summary=1
+        run: |
+          set -o pipefail
+          make test PRESET=san ARGS=-VV | grep --color=always --line-buffered -E "FAILED|$"
+      - name: Check ASan and UBSan logs
+        if: ${{ !cancelled() && steps.build-san.outcome == 'success' }}
+        run: |
+          LOG_FILE=build/san/Testing/Temporary/LastTest.log
+          if grep -qE "\w+Sanitizer:|runtime error:" "$LOG_FILE"; then
+            grep --color=always -E "\w+Sanitizer:|runtime error:|$" "$LOG_FILE"
+            exit 1
+          else
+            echo "No ASan or UBSan issues detected."
+          fi
 
   build-and-test-result:
     runs-on: ubuntu-latest
